### ISSUE TITLE
Обработчики событий ввода в RenderControl

### ISSUE THREAD

**Issue by Notrum666** [nstu-ItCanDraw/ItCanDraw#26]
Создать обработчики событий в RenderControl для следующих событий:
-Нажатие клавиши
-Отжатие клавиши
-Нажатие кнопки мыши
-Отжатие кнопки мыши
-Движение мыши
-Вращение колеса мыши

Проверить какие из этих событий забагованные и не выбрасываются из-за того что GLWPFControl (контрол из OpenTK) забагованный и их не выбрасывает, те события, что не выбрасываются - изменить на Preview и проверить что теперь выбрасываются

соответственно прокидывание событий в классе MainWindow надо убрать

**Comment by Wact** [comment]
> Проверить какие из этих событий забагованные и не выбрасываются

Как это можно проверить?

**Comment by Notrum666** [comment]
на примере события нажатия мыши (но оно, если память не изменяет, работает): создаёшь обработчик этого события, ставишь брейкпоинт, запускаешь, кликаешь мышью в контроле, если брейкпоинт не сработал - событие съелось контролом от OpenTK, т.е. оно забагованное
