### ISSUE TITLE
Zoom камеры по вращению колеса мыши

### ISSUE THREAD

**Issue by Notrum666** [nstu-ItCanDraw/ItCanDraw#43]
В обработчике события вращения колеса мыши вызывать соответствующую функцию Zoom у объекта камеры в RenderControl, передавая точку, в которой находится курсор пользователя (в виртуальном пространстве, т.е. сперва переведя экранную координату в виртуальную) и передавая правильный коэффициент в зависимости от направления вращения колеса (вверх - приближение камеры, вниз - отдаление камеры)

**Comment by Wact** [comment]
Если значение дельты отрицательное, то будет выброшено исключение. Почему? У нас не будет зум только на увеличение, но не на уменьшение?
![изображение](https://user-images.githubusercontent.com/26605975/158044938-4f9f27f0-5e6e-45d9-a9e7-58f468a8fc6d.png)

**Comment by Wact** [comment]
> передавая точку, в которой находится курсор пользователя (в виртуальном пространстве, т.е. сперва переведя экранную координату в виртуальную)

Нужно ли это делать в обработчике? `recalculateMatrixes()` не делает этого?

**Comment by Wact** [comment]
И как я могу убедиться, что код, который я написал, работает?

**Comment by Notrum666** [comment]
1) см. summary перед функцией, там описано что означают какие значения дельты
2) опять же см. summary, функция Zoom ожидает точку в локальном пространстве (по смыслу, можно было, конечно, сделать перевод внутри, но вдруг понадобится когда-то вызывать эту функцию по виртуальным координатам, тогда будет два перевода - перевод из виртуальных в экранные координаты при вызове функции и обратно внутри функции), но так как WPF ни о каком виртуальном пространстве и знать не знает - надо точку на экране переводить, перевод осуществляется с помощью соответствующей функции у класса камеры
3) сейчас рендерится пустая заглушка для документа - поле 200 на 200 виртуальных пикселей, при том камера по умолчанию 300 виртуальных пикселей по высоте, так что если ты начнёшь приближаться или отдаляться - ты увидишь перемещение белого квадрата на экране

**Comment by Notrum666** [comment]
а ещё я понял что там неправильная формула пересчёта позиции, исправлю чуть позже

**Comment by Wact** [comment]
Это в коде:
```
/// <summary>
        /// Zooms camera for given delta, keeping given virtual point at the same place, delta > 1 means zoom in and delta < 0 means zoom out
        /// </summary>
        /// <param name="point">Point that will be the same in virtual space, pass camera's position too zoom into or out of camera center</param>
        /// <param name="delta">Delta to zoom for, must be positive, value > 1 means zoom in and value < 1 means zoom out</param>
```

В первом предложении ошибка про дельту меньше нуля?

**Comment by Notrum666** [comment]
упс, да, там меньше единицы должно быть, видимо, писать этот код в 7 утра всё таки было не очень идеей

**Comment by Wact** [comment]
Хочу получать координаты с помощью функции GetPosition(), аргументом в которой является объект, относительно которого смотрится положение курсора. Это не есть виртуальные координаты? Нужно ли мне сначала результат GetPosition() переводить в координаты на экране, а потом пользоваться функцией ScreenToWorld?
https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.input.mouseeventargs.getposition?view=windowsdesktop-6.0

**Comment by Notrum666** [comment]
GetPosition возвращает координаты в экранном пространстве, как и сказано в документации которую ты скинул - от левого верхнего угла указанного элемента вправо по Х вниз по У в пикселях, именно такой вход функция перевода из экранных координат в виртуальные и ожидает, виртуальные же координаты в свою очередь это координаты в виртуальном пространстве в котором мы рисуем, с центром в центре документа
